name: Build & Push to Staging Deploy Repository

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Add CNAME
        run: echo "cycas.dev" > src/CNAME
      - name: Push to Staging Repository
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.STAGING_TOKEN }}
          external_repository: bashar-515/cycas-site-staging
          publish_branch: main
          publish_dir: ./src
